# Generated by Django 3.1.4 on 2020-12-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Name',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
