# Generated by Django 3.1.4 on 2020-12-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20201223_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Platform',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
