# Generated by Django 3.1.4 on 2020-12-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_task_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Course',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
